/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/routes/__root'
import { Route as SignupRouteImport } from './app/routes/signup'
import { Route as SettingsRouteImport } from './app/routes/settings'
import { Route as ResetPasswordRouteImport } from './app/routes/reset-password'
import { Route as LoginRouteImport } from './app/routes/login'
import { Route as JobsRouteImport } from './app/routes/jobs'
import { Route as ForgotPasswordRouteImport } from './app/routes/forgot-password'
import { Route as DashboardRouteImport } from './app/routes/dashboard'
import { Route as IndexRouteImport } from './app/routes/index'
import { Route as ToolsSplitRouteImport } from './app/routes/tools/split'
import { Route as ToolsRotateRouteImport } from './app/routes/tools/rotate'
import { Route as ToolsReorderRouteImport } from './app/routes/tools/reorder'
import { Route as ToolsOcrRouteImport } from './app/routes/tools/ocr'
import { Route as ToolsMergeRouteImport } from './app/routes/tools/merge'
import { Route as ToolsCompressRouteImport } from './app/routes/tools/compress'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const JobsRoute = JobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsSplitRoute = ToolsSplitRouteImport.update({
  id: '/tools/split',
  path: '/tools/split',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsRotateRoute = ToolsRotateRouteImport.update({
  id: '/tools/rotate',
  path: '/tools/rotate',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsReorderRoute = ToolsReorderRouteImport.update({
  id: '/tools/reorder',
  path: '/tools/reorder',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsOcrRoute = ToolsOcrRouteImport.update({
  id: '/tools/ocr',
  path: '/tools/ocr',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsMergeRoute = ToolsMergeRouteImport.update({
  id: '/tools/merge',
  path: '/tools/merge',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsCompressRoute = ToolsCompressRouteImport.update({
  id: '/tools/compress',
  path: '/tools/compress',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tools/compress': typeof ToolsCompressRoute
  '/tools/merge': typeof ToolsMergeRoute
  '/tools/ocr': typeof ToolsOcrRoute
  '/tools/reorder': typeof ToolsReorderRoute
  '/tools/rotate': typeof ToolsRotateRoute
  '/tools/split': typeof ToolsSplitRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tools/compress': typeof ToolsCompressRoute
  '/tools/merge': typeof ToolsMergeRoute
  '/tools/ocr': typeof ToolsOcrRoute
  '/tools/reorder': typeof ToolsReorderRoute
  '/tools/rotate': typeof ToolsRotateRoute
  '/tools/split': typeof ToolsSplitRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/jobs': typeof JobsRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/tools/compress': typeof ToolsCompressRoute
  '/tools/merge': typeof ToolsMergeRoute
  '/tools/ocr': typeof ToolsOcrRoute
  '/tools/reorder': typeof ToolsReorderRoute
  '/tools/rotate': typeof ToolsRotateRoute
  '/tools/split': typeof ToolsSplitRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/tools/compress'
    | '/tools/merge'
    | '/tools/ocr'
    | '/tools/reorder'
    | '/tools/rotate'
    | '/tools/split'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/tools/compress'
    | '/tools/merge'
    | '/tools/ocr'
    | '/tools/reorder'
    | '/tools/rotate'
    | '/tools/split'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/forgot-password'
    | '/jobs'
    | '/login'
    | '/reset-password'
    | '/settings'
    | '/signup'
    | '/tools/compress'
    | '/tools/merge'
    | '/tools/ocr'
    | '/tools/reorder'
    | '/tools/rotate'
    | '/tools/split'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JobsRoute: typeof JobsRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  ToolsCompressRoute: typeof ToolsCompressRoute
  ToolsMergeRoute: typeof ToolsMergeRoute
  ToolsOcrRoute: typeof ToolsOcrRoute
  ToolsReorderRoute: typeof ToolsReorderRoute
  ToolsRotateRoute: typeof ToolsRotateRoute
  ToolsSplitRoute: typeof ToolsSplitRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jobs': {
      id: '/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof JobsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/split': {
      id: '/tools/split'
      path: '/tools/split'
      fullPath: '/tools/split'
      preLoaderRoute: typeof ToolsSplitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/rotate': {
      id: '/tools/rotate'
      path: '/tools/rotate'
      fullPath: '/tools/rotate'
      preLoaderRoute: typeof ToolsRotateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/reorder': {
      id: '/tools/reorder'
      path: '/tools/reorder'
      fullPath: '/tools/reorder'
      preLoaderRoute: typeof ToolsReorderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/ocr': {
      id: '/tools/ocr'
      path: '/tools/ocr'
      fullPath: '/tools/ocr'
      preLoaderRoute: typeof ToolsOcrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/merge': {
      id: '/tools/merge'
      path: '/tools/merge'
      fullPath: '/tools/merge'
      preLoaderRoute: typeof ToolsMergeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/compress': {
      id: '/tools/compress'
      path: '/tools/compress'
      fullPath: '/tools/compress'
      preLoaderRoute: typeof ToolsCompressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JobsRoute: JobsRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  ToolsCompressRoute: ToolsCompressRoute,
  ToolsMergeRoute: ToolsMergeRoute,
  ToolsOcrRoute: ToolsOcrRoute,
  ToolsReorderRoute: ToolsReorderRoute,
  ToolsRotateRoute: ToolsRotateRoute,
  ToolsSplitRoute: ToolsSplitRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
